# Machine learning
## Numpy Assignment

1. What is a Python library? Why do we use Python libraries?



### write answer here
A Python library is a collection of pre-written code and functions that extend the capabilities of Python programming language. Libraries provide reusable modules and functions that developers can easily incorporate into their Python code to perform specific tasks without having to write the code from scratch.

- use for
- code reusability
- efficiency
- modular code maintability
- more focus on domain-specifice problem
- community-contributions


2. What is the difference between Numpy array and List?


###### write answer here
NumPy arrays and Python lists are both data structures used to store collections of elements, but they have several differences in terms of functionality, performance, and usage.

1. **Memory Efficiency:**
   - NumPy arrays store elements of the same data type in contiguous memory, providing better memory efficiency.
   - Python lists can store elements of different data types, leading to less efficient memory usage.

2. **Performance:**
   - NumPy arrays are optimized for numerical operations and perform faster than Python lists, especially with large datasets.
   - NumPy operations are implemented in C, providing better performance compared to Python lists.

3. **Functionality:**
   - NumPy arrays offer extensive mathematical functions and operations for array manipulation, while Python lists are more versatile for general-purpose programming.

4. **Ease of Use:**
   - NumPy arrays have concise syntax for mathematical operations, and Python lists are more user-friendly for general programming tasks.

5. **Type Stability:**
   - NumPy arrays have a fixed data type for all elements, ensuring type stability and efficient computation.
   - Python lists can store elements of different data types, potentially leading to type coercion and slower performance.

In summary, NumPy arrays excel in numerical computations, providing memory efficiency and performance, while Python lists are more versatile for general-purpose programming. The choice depends on the specific needs of the task.

3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]



In [19]:
# shape
import numpy as np
arr = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
    ]
#initial type of arr
print(type(arr))

# convert arr in numpy arr
np_arr = np.array(arr)

#find the shape the array
shape = np_arr.shape

# find the size of array
size = np_arr.size 

# find the dimension of array
dim = np_arr.ndim

#print all

print(f" shape of arr {shape} ")

print(f" size of arr {size}")

print(f" Dimension of arr {dim}")

<class 'list'>
 shape of arr (3, 4) 3
 size of arr 12
 Dimension of arr 2



4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]



In [12]:
arr = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
    ]

# access first arr using list 
print(f"access using list {arr[0]}")

# using numpy
arr = np.array(arr)

print(f'access using numpy {arr[0]}')

access using list [1, 2, 3, 4]
access using numpy [1 2 3 4]



5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [17]:
arr =[
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
    ]
np_arr = np.array(arr)

# access 3rd row and 4th column element is 12
print(f'access 3rd row and 4th column element is {np_arr[2][3]}')

access 3rd row and 4th column element 12


6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]


In [22]:
arr = np_arr

for row in range(0,arr.shape[0]):
    for col in range(0,arr.shape[1]):
        if col%2 !=0:
            print(arr[row][col],end=" ")
    print("")

2 4 
6 8 
10 12 


7. How can you generate a random 3x3 matrix with values between 0 and 1?




In [27]:
import random

matrix = np.zeros((3,3))
print(matrix)

print(round(random.random(),1))


for row in range(3):
    for col in range(3):
        num =  round(random.random(),1)
        matrix[row][col] = num

print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
0.4
[[0.3 0.4 0.7]
 [0.7 0.7 0.7]
 [0.6 0.2 0.4]]


8. Describe the difference between np.random.rand and np.random.randn?

In [31]:
print(np.random.rand()) # np.random.rand give the range between 0 to 1.
print((np.random.randn())) # np.random.rand give the value which follow the normal distribution function mean =0 ,std=1

0.32271090779888123
-1.6409048567843656


9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]



In [33]:
original_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Using np.newaxis
new_array = original_array[:, :, np.newaxis]
# OR using np.expand_dims
new_array = np.expand_dims(original_array, axis=2)

print(new_array)
print(new_array.ndim)


[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]
3



10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]


In [34]:
original_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

transposed_array = original_array.T
# OR ?
transposed_array = np.transpose(original_array)

print(transposed_array)


[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]




11. Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


Perform the following operation using Python1
- index wise multiplication
- Matix multiplication
- Add both the matics
- Subtact matrix A and B
- Divide Matrix B by A




In [35]:
import numpy as np

# Define matrices A and B
matrix_A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrix_B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Index-wise multiplication
index_wise_multiplication = matrix_A * matrix_B

# Matrix multiplication
matrix_multiplication = np.dot(matrix_A, matrix_B.T)

# Addition
matrix_addition = matrix_A + matrix_B

# Subtraction
matrix_subtraction = matrix_A - matrix_B

# Division (element-wise)
matrix_division = matrix_B / matrix_A

print("Index-wise multiplication:\n", index_wise_multiplication)
print("Matrix multiplication:\n", matrix_multiplication)
print("Matrix addition:\n", matrix_addition)
print("Matrix subtraction:\n", matrix_subtraction)
print("Matrix division:\n", matrix_division)


Index-wise multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matrix multiplication:
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
Matrix addition:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Matrix subtraction:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Matrix division:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12.  Which function in Numpy can be used to swap the byte order of an array?



In [37]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype=np.int32)
swapped_arr = arr.byteswap()
print(swapped_arr)

[16777216 33554432 50331648 67108864]


13.  What is the significance of the np.linalg.inv function?



The np.linalg.inv function in NumPy is used to compute the inverse of a matrix. 
The inverse of a matrix A, denoted as A^-1, is such that A * A^-1 = A^-1 * A = I, where I is the identity matrix.

In [38]:
import numpy as np

# Create a square matrix
matrix_A = np.array([[2, 1], [7, 4]])

# Compute the inverse of the matrix
inverse_A = np.linalg.inv(matrix_A)

# Print the original matrix and its inverse
print("Original Matrix A:\n", matrix_A)
print("Inverse of Matrix A:\n", inverse_A)

# Verify that the product of A and A_inv is the identity matrix
identity_matrix = np.dot(matrix_A, inverse_A)
print("Product of A and its Inverse (should be an identity matrix):\n", identity_matrix)


Original Matrix A:
 [[2 1]
 [7 4]]
Inverse of Matrix A:
 [[ 4. -1.]
 [-7.  2.]]
Product of A and its Inverse (should be an identity matrix):
 [[1. 0.]
 [0. 1.]]


14. What does the np.reshape function do, and how is it used?


In [40]:
# change the shape of an array without changing its data.


arr = np.array([[1, 2, 3], [4, 5, 6]])
reshaped_arr = np.reshape(arr, (3, 2))
print(reshaped_arr)

[[1 2]
 [3 4]
 [5 6]]



15. What is broadcasting in Numpy

Broadcasting in NumPy refers to the ability of NumPy to perform operations on arrays of different shapes and sizes. It allows you to perform element-wise operations between arrays of different shapes without explicitly reshaping them. NumPy automatically broadcasts the smaller array to match the shape of the larger one. This makes it easier to perform operations on arrays of different dimensions without the need for explicit looping.

In [41]:

# Create a 3x3 matrix
matrix_A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create a 1D array to be added to each column of the matrix
column_addition = np.array([10, 20, 30])

# Use broadcasting to add the 1D array to each column of the matrix
result = matrix_A + column_addition

# Print the original matrix, the 1D array, and the result
print("Original Matrix A:\n", matrix_A)
print("1D Array for Broadcasting:\n", column_addition)
print("Result after Broadcasting:\n", result)


Original Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
1D Array for Broadcasting:
 [10 20 30]
Result after Broadcasting:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]
